apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-time-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-time-service
  template:
    metadata:
      labels:
        app: simple-time-service
    spec:
      containers:
      - name: simple-time-service
        image: aramesh166/simple-time-service:latest
        ports:
        - containerPort: 5000
---        
apiVersion: v1
kind: Service
metadata:
  name: simple-time-service
spec:
  selector:
    app: simple-time-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: ClusterIP

#If using NodePort service
---

# apiVersion: v1
# kind: Service
# metadata:
#   name: simple-time-service
# spec:
#   selector:
#     app: simple-time-service
#   ports:
#   - protocol: TCP
#     port: 80
#     targetPort: 5000
#   type: NodePort
